### ISSUE TITLE
[Suggestions] Method of publishing the website

### ISSUE THREAD

**Issue by Keritial** [TheNightmareX/me#1]
~~***纯纯闲得无聊写的，建议无视以下任何内容。***~~

Considering the content below is well-known, I just want to ask why don't do it.

~~*And, most importantly, forgive my grammar mistakes, I apologize for that but I still can't avoid it.(可以的话指出来嘛喵呜呜呜呜呜(也许我需要 Grammarly(逃)))*~~

Currently, your website seems to be built locally and pushed to the `gh-pages` branch, then GitHub uses Actions to deploy it to `https://thenightmarex.github.io/me`, which is a sub-directory (`/me`) of your Pages.

But wouldn't it be better if deploy the website at the root (`/`) of your Pages? For example, `https://thenightmarex.github.io`. To achieve that, the only thing needed to do is to rename your repository from `me` to `thenightmarex.github.io`. It will have effect upon next deployment.

Speaking of Actions, there're two methods of deploying a website on Pages, and they both use Actions. One legacy way is pushing your built website static files (or Jekyll) to specific branch and then Actions deploys it on every push. The other is directly deploy a website through Actions. For example, you can write a Acrions workflow that builds and deploys it.

**Comment by Char2sGu** [comment]
I'm actually using `ng deploy` for deployment which is quite convenient for me and I have the choice to decide whether and when to deploy. CI doesn't look attractive to me.

It's an intentional decitsion to deploy at `/me` instead of `/` to avoid path conflicts. What if my personal website have a `/blogs` route but there is another repository deployed at the `/blogs` path if my personal website is deployed at `/`?

I'll close this issue as solved for now. Feel free to reopen it if you have any other thoughts.

**Comment by Keritial** [comment]
It makes sense for me, thanks for spending time explaining for me.
